### ISSUE TITLE
NullPointerException being thrown in "com.newrelic.agent.Transaction.finishSegment"

### ISSUE THREAD

**Issue by gillesbergerp** [newrelic/newrelic-java-kotlin-coroutines#36]
## Description

We experience ``NullPointerException``s when using the coroutine extension with Java agent version 8.15.0. Removing the extension (but staying on the same agent version) does not result in the problem

## Relevant Logs / Console output

```
java.lang.NullPointerException:
 Cannot invoke 
"com.newrelic.agent.Transaction.finishSegment(com.newrelic.agent.Segment,
 java.lang.Throwable, com.newrelic.agent.tracers.Tracer, String)" 
because the return value of 
"com.newrelic.agent.TransactionActivity.getTransaction()" is null
	at com.newrelic.agent.Segment$1.run(Segment.java:203)
	at 
com.newrelic.agent.ExpirationService.expireSegmentInline(ExpirationService.java:47)
	at com.newrelic.agent.Segment.finish(Segment.java:215)
	at com.newrelic.agent.Segment.end(Segment.java:144)
	at 
com.nr.agent.mongo.NRCallbackWrapper.onResult(NRCallbackWrapper.java:48)
	at 
com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:47)
	at 
com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:97)
	at 
com.mongodb.internal.async.function.RetryingAsyncCallbackSupplier$RetryingCallback.onResult(RetryingAsyncCallbackSupplier.java:116)
	at 
com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:47)
	at 
com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:97)
	at 
com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:47)
	at 
com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:97)
	at 
com.mongodb.internal.operation.FindOperation.lambda$exceptionTransformingCallback$6(FindOperation.java:369)
	at 
com.mongodb.internal.operation.AsyncOperationHelper.lambda$transformingReadCallback$19(AsyncOperationHelper.java:442)
	at 
com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:47)
	at 
com.mongodb.internal.connection.LoadBalancedServer$LoadBalancedServerProtocolExecutor.lambda$executeAsync$0(LoadBalancedServer.java:186)
	at 
com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:47)
	at 
com.mongodb.internal.connection.CommandProtocolImpl.lambda$executeAsync$0(CommandProtocolImpl.java:88)
	at 
com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.lambda$sendAndReceiveAsync$1(DefaultConnectionPool.java:802)
	at 
com.mongodb.internal.connection.UsageTrackingInternalConnection.lambda$sendAndReceiveAsync$1(UsageTrackingInternalConnection.java:155)
	at 
com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:47)
	at 
com.mongodb.internal.connection.InternalStreamConnection.lambda$sendCommandMessageAsync$0(InternalStreamConnection.java:555)
	at 
com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:849)
	at 
com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:812)
	at 
com.mongodb.internal.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:671)
	at 
com.mongodb.internal.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:668)
	at 
com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:252)
	at 
com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:235)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Unknown Source)
	at 
java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(Unknown 
Source)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(Unknown 
Source)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(Unknown 
Source)
	at 
com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.read(AsynchronousSocketChannelStream.java:148)
	at 
com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:124)
	at 
com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:113)
	at 
com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:668)
	at 
com.mongodb.internal.connection.InternalStreamConnection.access$600(InternalStreamConnection.java:98)
	at 
com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:802)
	at 
com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:786)
	at 
com.mongodb.internal.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:671)
	at 
com.mongodb.internal.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:668)
	at 
com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:252)
	at 
com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.comple<!--EndFragment-->
```

## Your Environment

* NewRelic Java Agent 8.15.0
* JRE 17
* Kotlin 1.9.20

**Comment by dhilpipre** [comment]
We are working on this problem.  it results from problems with the Java Agent and the Kotlin-Coroutines-Suspends.jar.  
As a workaround, remove the Kotlin-Coroutines-Suspends.jar from the extensions directory and restart.  This should eliminate the problem but will result in Suspend methods not being tracked.

All other extension are fine and do not cause problems.

**Comment by gillesbergerp** [comment]
Thanks for the fast reply. Is there an ETA for when a fix might be available?

**Comment by dhilpipre** [comment]
The problem seems to stem from a problem when the Java Agent retransforms some Kotlin classes.  I can't give an ETA until I have been able to work with them on fixing that problem but indications are that it might be a while.

**Comment by gillesbergerp** [comment]
@dhilpipre, can you share an update on this issue?

**Comment by dhilpipre** [comment]
After a long investigation the Java Agent team was able to find the problem and fix it.  This should eliminate the NullPointerExceptions.   
Please use Release https://github.com/newrelic/newrelic-java-kotlin-coroutines/releases/tag/v1.0.7
and update the Java Agent to 8.1.19.

**Comment by dhilpipre** [comment]
sorry, typo.  8.19.0

**Comment by MT-Jacobs** [comment]
I'm still getting this behavior with 8.19.0 and the 1.0.7 extension.

For those with access to our company's New Relic space - https://onenr.io/0VwgLMdkORJ

Error message: "TransactionActivity is gone"

Stacktrace -

```
	com.newrelic.agent.Transaction.getTransactionActivity(Transaction.java:924)
	at 	com.newrelic.agent.Transaction.startSegment(Transaction.java:2316)
	at 	com.newrelic.agent.TransactionApiImpl.startSegment(TransactionApiImpl.java:476)
	at 	com.newrelic.agent.TransactionApiImpl.startSegment(TransactionApiImpl.java:456)
	at 	com.nr.lettuce6.instrumentation.NRHolder.startSegment(NRHolder.java:38)
	at 	com.nr.lettuce6.instrumentation.NRSubscribeConsumer.accept(NRSubscribeConsumer.java:24)
	at 	com.nr.lettuce6.instrumentation.NRSubscribeConsumer.accept(NRSubscribeConsumer.java:13)
	at 	reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onSubscribe(FluxPeekFuseable.java:807)
	at 	reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70)
	at 	reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70)
	at 	io.lettuce.core.RedisPublisher$State$1.subscribe(RedisPublisher.java:518)
	at 	io.lettuce.core.RedisPublisher$RedisSubscription.subscribe(RedisPublisher.java:231)
	at 	io.lettuce.core.RedisPublisher.subscribe(RedisPublisher.java:130)
	at 	reactor.core.publisher.MonoFromPublisher.subscribe(MonoFromPublisher.java:64)
	at 	reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
	at 	reactor.core.publisher.FluxRetry$RetrySubscriber.resubscribe(FluxRetry.java:120)
	at 	reactor.core.publisher.MonoRetry.subscribeOrReturn(MonoRetry.java:50)
	at 	reactor.core.publisher.Mono.subscribe(Mono.java:4552)
	at 	reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:430)
	at 	reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:335)
	at 	reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:294)
	at 	reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:373)
	at 	reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201)
	at 	reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83)
	at 	reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:68)
	at 	reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at 	io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
	at 	reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at 	reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at 	io.micronaut.core.propagation.PropagatedContext.lambda$wrap$4(PropagatedContext.java:228)
	at 	io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)
	at 	io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:203)
	at 	java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at 	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at 	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at 	java.base/java.lang.Thread.run(Thread.java:840)
```

It's possible this is related to something not explicitly Kotlin, such as reactor, lettuce, or micrometer. I'll see what I can find.

**Comment by MT-Jacobs** [comment]
Above might be a slightly different issue, though note that I am finding NPEs with logs as well - https://onenr.io/0BR6oka5GjO

```
"    at com.newrelic.agent.Segment$1.run(Segment.java:203)\n    at com.newrelic.agent.ExpirationService.expireSegmentInline(ExpirationService.java:47)\n    at com.newrelic.agent.Segment.finish(Segment.java:215)\n    at com.newrelic.agent.Segment.end(Segment.java:144)\n    at com.nr.lettuce6.instrumentation.NRHolder.end(NRHolder.java:56)\n    at com.nr.lettuce6.instrumentation.NRSignalTypeConsumer.accept(NRSignalTypeConsumer.java:24)\n    at com.nr.lettuce6.instrumentation.NRSignalTypeConsumer.accept(NRSignalTypeConsumer.java:13)\n    at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:146)\n    at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.cancel(FluxDoFinally.java:135)\n    at reactor.core.publisher.Operators.terminate(Operators.java:1328)\n    at reactor.core.publisher.StrictSubscriber.cancel(StrictSubscriber.java:155)\n    at kotlinx.coroutines.reactive.AwaitKt$awaitOne$2$1$onNext$1.invoke(Await.kt:240)\n    at kotlinx.coroutines.reactive.AwaitKt$awaitOne$2$1$onNext$1.invoke(Await.kt:239)\n    at kotlinx.coroutines.reactive.AwaitKt$awaitOne$2$1.withSubscriptionLock(Await.kt:310)\n    at kotlinx.coroutines.reactive.AwaitKt$awaitOne$2$1.onNext(Await.kt:239)\n    at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)\n    at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)\n    at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)\n    at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)\n    at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)\n    at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)\n    at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onNext(RedisPublisher.java:890)\n    at io.lettuce.core.RedisPublisher$RedisSubscription.onNext(RedisPublisher.java:291)\n    at io.lettuce.core.RedisPublisher$SubscriptionCommand.doOnComplete(RedisPublisher.java:777)\n    at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:65)\n    at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63)\n    at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:745)\n    at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:680)\n    at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:597)\n    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)\n    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)\n    at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1338)\n    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387)\n    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)\n    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)\n    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)\n    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\n    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)\n    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)\n    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)\n    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)\n    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)\n    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)\n    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)\n    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)\n    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)\n    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n    at java.base/java.lang.Thread.run(Thread.java:840)"
```

**Comment by dhilpipre** [comment]
Hi Matt, 

I will have to go back to the Java Agent team to see if they can identify where the problem still exists.  We thought that the problem was related when the agent instruments a Suspend function.  
For now, remove the Kotlin-Coroutines-Suspend.jar from the extensions directory to get rid of the exceptions.

**Comment by SenPavel** [comment]
Hi, We are experiencing the same issue as described above. We had a code, which was responsible for reporting the external HTTP call (`NewRelic.getAgent().tracedMethod.reportAsExternal`), encountered an exception and produced the following stack trace:

```
	java.lang.IllegalStateException: TransactionActivity is gone
	at com.newrelic.agent.Transaction.getTransactionActivity(Transaction.java:924)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Original Stack Trace:
		at com.newrelic.agent.Transaction.getTransactionActivity(Transaction.java:924)
		at com.newrelic.agent.AgentImpl.getTracedMethod(AgentImpl.java:56)
		at com.newrelic.agent.AgentImpl.getTracedMethod(AgentImpl.java:32)
		at org.springframework.data.redis.cache.RedisCache.lambda$retrieve$1(RedisCache.java:309)
		at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
		at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
		at reactor.core.publisher.MonoToCompletableFuture.onNext(MonoToCompletableFuture.java:64)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
		at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:176)
		at kotlinx.coroutines.reactor.MonoCoroutine.onCompleted(Mono.kt:99)
		at kotlinx.coroutines.AbstractCoroutine.onCompletionInternal(AbstractCoroutine.kt:92)
		at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:287)
		at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:887)
		at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:859)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
		at com.newrelic.instrumentation.kotlin.coroutines_19.NRContinuationWrapper.resumeWith(NRContinuationWrapper.java:47)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at com.newrelic.instrumentation.kotlin.coroutines_19.NRContinuationWrapper.resumeWith(NRContinuationWrapper.java:47)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:35)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:101)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at com.newrelic.instrumentation.kotlin.coroutines_19.NRContinuationWrapper.resumeWith(NRContinuationWrapper.java:47)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
		at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
		at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:243)
		at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:147)
		at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
		at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$kotlinx_coroutines_core(CancellableContinuationImpl.kt:504)
		at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$kotlinx_coroutines_core$default(CancellableContinuationImpl.kt:493)
		at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:359)
		at kotlinx.coroutines.future.ContinuationHandler.apply(Future.kt:186)
		at kotlinx.coroutines.future.ContinuationHandler.apply(Future.kt:178)
		at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
		at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
		at org.apache.solr.client.solrj.impl.Http2SolrClient$1.lambda$onHeaders$0(Http2SolrClient.java:489)
		at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:380)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.base/java.lang.Thread.run(Unknown Source)
``` 

Then we found out that we no longer use these metrics, therefore removed them, but other exceptions started to appear:
```
Exception in thread "reactor-http-epoll-1" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[Dispatchers.Unconfined, Continuation at {Completed}@31fd60e0. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:130)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:250)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:147)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$kotlinx_coroutines_core(CancellableContinuationImpl.kt:504)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$kotlinx_coroutines_core$default(CancellableContinuationImpl.kt:493)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:359)
	at kotlinx.coroutines.reactor.MonoKt$awaitSingleOrNull$2$1.onComplete(Mono.kt:52)
	at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:223)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:223)
	at reactor.core.publisher.SerializedSubscriber.onComplete(SerializedSubscriber.java:146)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onComplete(FluxRetryWhen.java:204)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2231)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:246)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2231)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:549)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:223)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:209)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:371)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:724)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onComplete(FluxFlattenIterable.java:273)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:483)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:275)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:419)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:445)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:499)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:800)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1515)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1378)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1427)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: ["com.newrelic.agent.transaction.TransactionTimer.markTxaFinishTime(com.newrelic.agent.tracers.Tracer)" because "this.transactionTime" is null
	at com.newrelic.agent.Transaction.checkFinishTransaction(Transaction.java:2451)
	at com.newrelic.agent.Transaction.linkTxOnThread(Transaction.java:1497)
	at com.newrelic.agent.TokenImpl.link(TokenImpl.java:91)
	at com.newrelic.instrumentation.kotlin.coroutines_19.NRContinuationWrapper.resumeWith(NRContinuationWrapper.java:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:233)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:175)
``` 

Our environment:
NewRelic Java Agent 8.19.0
NewRelic Java Agent Koltin coroutines extension 1.7.0
JRE 21
Kotlin 2.1.20
Spring WebFlux 3.3.4
